package nl.saxion.nena.opentcs.commadapter.ros2.control_center.gui_components;
import nl.saxion.nena.opentcs.commadapter.ros2.control_center.lib.InputValidationLib;
import javax.swing.text.Document;

public final class CoordinateInputPanel
        extends TextInputPanel {

    /**
     * If the panel is resetable this is the value the input is set to when
     * doReset() is called.
     */
    private Object resetValue;
    private boolean xInputFieldValid = true;
    private boolean yInputFieldValid = true;
    private boolean zInputFieldValid = true;

    /**
     * Create a new <code>TripleTextInputPanel</code>.
     * @param title Title of the panel
     */
    private CoordinateInputPanel(String title) {
        super(title);
        initComponents();
    }

    /**
     * Enable input validation against the given regular expressions.
     * If a format string is <code>null</code> the related text field is not
     * validated.
     * @see InputPanel#addValidationListener
     */
    private void enableInputValidation() {
        String format = InputValidationLib.getIsDoubleRegex();

        xInputField.getDocument().addDocumentListener(new TextInputValidator(format));
        yInputField.getDocument().addDocumentListener(new TextInputValidator(format));
        zInputField.getDocument().addDocumentListener(new TextInputValidator(format));
    }

    @Override
    protected void captureInput() {
        input = new String[] {xInputField.getText(),
                yInputField.getText(),
                zInputField.getText()};
    }

    @Override
    public void doReset() {
        input = resetValue;
    }

    /**
     * Mark the input of the specified <code>Document</code> as valid, if this
     * Document belongs to one of the three text fields in this panel.
     * If <code>valid</code> is <code>true</code> the validity of the other
     * two documents is checked, too. Only if all three text fields contain valid
     * input, the whole input of the panel is marked as valid.
     *
     * @see TextInputPanel#setInputValid(boolean, javax.swing.text.Document)
     * @param valid true, if the content of the <code>Document</code> is valid
     * @param doc the <code>Document</code>
     */
    @Override
    protected void setInputValid(boolean valid, Document doc) {
        // Find out to which input field the document belongs and check the others
        boolean allValid = valid;
        if (doc == xInputField.getDocument()) {
            xInputFieldValid = valid;
            if (!(yInputFieldValid && zInputFieldValid)) {
                allValid = false;
            }
        }
        else if (doc == yInputField.getDocument()) {
            yInputFieldValid = valid;
            if (!(xInputFieldValid && zInputFieldValid)) {
                allValid = false;
            }
        }
        else if (doc == zInputField.getDocument()) {
            zInputFieldValid = valid;
            if (!(xInputFieldValid && yInputFieldValid)) {
                allValid = false;
            }
        }
        else {
            allValid = false;
        }
        setInputValid(allValid);
    }

    // CHECKSTYLE:OFF
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        instructionLabel = new javax.swing.JLabel();
        xLabel = new javax.swing.JLabel();
        xInputField = new javax.swing.JTextField();
        xUnitLabel = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        yInputField = new javax.swing.JTextField();
        yUnitLabel = new javax.swing.JLabel();
        zLabel = new javax.swing.JLabel();
        zInputField = new javax.swing.JTextField();
        zUnitLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(280, 150));
        setLayout(new java.awt.GridBagLayout());

        instructionLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("nl/saxion/nena/opentcs/commadapter/ros2/Bundle"); // NOI18N
        instructionLabel.setText(bundle.getString("ros2CommAdapterPanel.dialog_dispatchVehicleToCoordinate.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(instructionLabel, gridBagConstraints);

        xLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        xLabel.setText("X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(xLabel, gridBagConstraints);

        xInputField.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        xInputField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        xInputField.setText("initial_value");
        xInputField.setName("xInputField"); // NOI18N
        xInputField.setPreferredSize(new java.awt.Dimension(60, 30));
        xInputField.setRequestFocusEnabled(false);
        xInputField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                xInputFieldFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(xInputField, gridBagConstraints);
        xInputField.getAccessibleContext().setAccessibleName("");

        xUnitLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        xUnitLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        xUnitLabel.setText(bundle.getString("ros2CommAdapterPanel.unit_meter")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(xUnitLabel, gridBagConstraints);

        yLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        yLabel.setText("Y");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(yLabel, gridBagConstraints);

        yInputField.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        yInputField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        yInputField.setText("initial_value");
        yInputField.setName("yInputField"); // NOI18N
        yInputField.setPreferredSize(new java.awt.Dimension(60, 30));
        yInputField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yInputFieldFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(yInputField, gridBagConstraints);
        yInputField.getAccessibleContext().setAccessibleName("");

        yUnitLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        yUnitLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        yUnitLabel.setText(bundle.getString("ros2CommAdapterPanel.unit_meter")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(yUnitLabel, gridBagConstraints);

        zLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        zLabel.setText("Z");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(zLabel, gridBagConstraints);

        zInputField.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        zInputField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        zInputField.setText("initial_value");
        zInputField.setName("zInputField"); // NOI18N
        zInputField.setPreferredSize(new java.awt.Dimension(60, 30));
        zInputField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                zInputFieldFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(zInputField, gridBagConstraints);
        zInputField.getAccessibleContext().setAccessibleName("");

        zUnitLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        zUnitLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        zUnitLabel.setText(bundle.getString("ros2CommAdapterPanel.unit_meter")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(zUnitLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void xInputFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_xInputFieldFocusGained
        xInputField.selectAll();
    }//GEN-LAST:event_xInputFieldFocusGained

    private void yInputFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yInputFieldFocusGained
        yInputField.selectAll();
    }//GEN-LAST:event_yInputFieldFocusGained

    private void zInputFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zInputFieldFocusGained
        zInputField.selectAll();
    }//GEN-LAST:event_zInputFieldFocusGained
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JTextField xInputField;
    private javax.swing.JLabel xLabel;
    private javax.swing.JLabel xUnitLabel;
    private javax.swing.JTextField yInputField;
    private javax.swing.JLabel yLabel;
    private javax.swing.JLabel yUnitLabel;
    private javax.swing.JTextField zInputField;
    private javax.swing.JLabel zLabel;
    private javax.swing.JLabel zUnitLabel;
    // End of variables declaration//GEN-END:variables
    //CHECKSTYLE:ON

    /**
     * See {@link InputPanel.Builder}.
     */
    public static class Builder
            implements InputPanel.Builder {

        /**
         * The panel's title.
         */
        private final String title;


        /**
         * Create a new builder.
         * @param title Title of the panel.
         */
        public Builder(String title) {
            this.title = title;
        }

        @Override
        public InputPanel build() {
            nl.saxion.nena.opentcs.commadapter.ros2.control_center.gui_components.CoordinateInputPanel panel = new nl.saxion.nena.opentcs.commadapter.ros2.control_center.gui_components.CoordinateInputPanel(title);
            panel.enableInputValidation();
            panel.xInputField.setText(null);
            panel.yInputField.setText(null);
            panel.zInputField.setText(null);
            return panel;
        }
    }
}
